const questions = [
  // Category 1 - Easy
  { category: 'Category 1', difficulty: 'easy', question: 'What is the capital of France?', options: ['Berlin', 'Madrid', 'Paris', 'Rome'], answer: 'Paris' },
  { category: 'Category 1', difficulty: 'easy', question: 'Which planet is closest to the Sun?', options: ['Venus', 'Mars', 'Mercury', 'Jupiter'], answer: 'Mercury' },
  { category: 'Category 1', difficulty: 'easy', question: 'What is the boiling point of water?', options: ['90°C', '100°C', '80°C', '70°C'], answer: '100°C' },
  { category: 'Category 1', difficulty: 'easy', question: 'Who wrote "Harry Potter"?', options: ['J.R.R. Tolkien', 'J.K. Rowling', 'George R.R. Martin', 'Suzanne Collins'], answer: 'J.K. Rowling' },
  { category: 'Category 1', difficulty: 'easy', question: 'Which ocean is the largest?', options: ['Atlantic', 'Indian', 'Pacific', 'Arctic'], answer: 'Pacific' },
  { category: 'Category 1', difficulty: 'easy', question: 'How many continents are there?', options: ['5', '6', '7', '8'], answer: '7' },
  { category: 'Category 1', difficulty: 'easy', question: 'What is 2 + 2?', options: ['3', '4', '5', '6'], answer: '4' },
  { category: 'Category 1', difficulty: 'easy', question: 'Who painted the Mona Lisa?', options: ['Vincent van Gogh', 'Pablo Picasso', 'Leonardo da Vinci', 'Claude Monet'], answer: 'Leonardo da Vinci' },
  { category: 'Category 1', difficulty: 'easy', question: 'Which country is known as the Land of the Rising Sun?', options: ['China', 'Japan', 'India', 'South Korea'], answer: 'Japan' },
  { category: 'Category 1', difficulty: 'easy', question: 'Which gas do plants absorb from the atmosphere?', options: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen'], answer: 'Carbon dioxide' },

  // Category 1 - Medium
  { category: 'Category 1', difficulty: 'medium', question: 'What year did World War II end?', options: ['1944', '1945', '1946', '1947'], answer: '1945' },
  { category: 'Category 1', difficulty: 'medium', question: 'What is the smallest planet in our solar system?', options: ['Earth', 'Venus', 'Mars', 'Mercury'], answer: 'Mercury' },
  { category: 'Category 1', difficulty: 'medium', question: 'Who is the author of "The Hobbit"?', options: ['J.R.R. Tolkien', 'J.K. Rowling', 'George R.R. Martin', 'Mark Twain'], answer: 'J.R.R. Tolkien' },
  { category: 'Category 1', difficulty: 'medium', question: 'What is the hardest natural substance on Earth?', options: ['Iron', 'Gold', 'Diamond', 'Silver'], answer: 'Diamond' },
  { category: 'Category 1', difficulty: 'medium', question: 'Which country hosted the 2016 Summer Olympics?', options: ['China', 'Brazil', 'UK', 'Japan'], answer: 'Brazil' },
  { category: 'Category 1', difficulty: 'medium', question: 'What is the chemical symbol for water?', options: ['O2', 'CO2', 'H2O', 'H2'], answer: 'H2O' },
  { category: 'Category 1', difficulty: 'medium', question: 'Who discovered penicillin?', options: ['Marie Curie', 'Alexander Fleming', 'Isaac Newton', 'Albert Einstein'], answer: 'Alexander Fleming' },
  { category: 'Category 1', difficulty: 'medium', question: 'What is the longest river in the world?', options: ['Amazon', 'Nile', 'Yangtze', 'Mississippi'], answer: 'Nile' },
  { category: 'Category 1', difficulty: 'medium', question: 'Which country is home to the kangaroo?', options: ['India', 'Australia', 'South Africa', 'Brazil'], answer: 'Australia' },
  { category: 'Category 1', difficulty: 'medium', question: 'What is the square root of 64?', options: ['6', '8', '10', '12'], answer: '8' },

  // Category 1 - Hard
  { category: 'Category 1', difficulty: 'hard', question: 'Who developed the theory of relativity?', options: ['Isaac Newton', 'Galileo', 'Albert Einstein', 'Marie Curie'], answer: 'Albert Einstein' },
  { category: 'Category 1', difficulty: 'hard', question: 'What is the speed of light?', options: ['300,000 km/s', '150,000 km/s', '1,000,000 km/s', '500,000 km/s'], answer: '300,000 km/s' },
  { category: 'Category 1', difficulty: 'hard', question: 'What is the capital of Canada?', options: ['Toronto', 'Ottawa', 'Vancouver', 'Montreal'], answer: 'Ottawa' },
  { category: 'Category 1', difficulty: 'hard', question: 'Who is the father of modern physics?', options: ['Albert Einstein', 'Isaac Newton', 'Galileo Galilei', 'Nikola Tesla'], answer: 'Isaac Newton' },
  { category: 'Category 1', difficulty: 'hard', question: 'What element has the atomic number 1?', options: ['Hydrogen', 'Helium', 'Oxygen', 'Nitrogen'], answer: 'Hydrogen' },
  { category: 'Category 1', difficulty: 'hard', question: 'Which country has the most pyramids?', options: ['Egypt', 'Sudan', 'Mexico', 'China'], answer: 'Sudan' },
  { category: 'Category 1', difficulty: 'hard', question: 'Who wrote the play "Hamlet"?', options: ['William Shakespeare', 'Jane Austen', 'Mark Twain', 'Charles Dickens'], answer: 'William Shakespeare' },
  { category: 'Category 1', difficulty: 'hard', question: 'What is the square root of 144?', options: ['10', '12', '14', '16'], answer: '12' },
  { category: 'Category 1', difficulty: 'hard', question: 'What is the largest mammal?', options: ['Elephant', 'Blue whale', 'Giraffe', 'Great white shark'], answer: 'Blue whale' },
  { category: 'Category 1', difficulty: 'hard', question: 'Who was the first person in space?', options: ['Neil Armstrong', 'Buzz Aldrin', 'Yuri Gagarin', 'John Glenn'], answer: 'Yuri Gagarin' },

  { category: 'Category 2', difficulty: 'easy', question: 'What is the capital of France?', options: ['Berlin', 'Madrid', 'Paris', 'Rome'], answer: 'Paris' },
  { category: 'Category 2', difficulty: 'easy', question: 'Which planet is closest to the Sun?', options: ['Venus', 'Mars', 'Mercury', 'Jupiter'], answer: 'Mercury' },
  { category: 'Category 2', difficulty: 'easy', question: 'What is the boiling point of water?', options: ['90°C', '100°C', '80°C', '70°C'], answer: '100°C' },
  { category: 'Category 2', difficulty: 'easy', question: 'Who wrote "Harry Potter"?', options: ['J.R.R. Tolkien', 'J.K. Rowling', 'George R.R. Martin', 'Suzanne Collins'], answer: 'J.K. Rowling' },
  { category: 'Category 2', difficulty: 'easy', question: 'Which ocean is the largest?', options: ['Atlantic', 'Indian', 'Pacific', 'Arctic'], answer: 'Pacific' },
  { category: 'Category 2', difficulty: 'easy', question: 'How many continents are there?', options: ['5', '6', '7', '8'], answer: '7' },
  { category: 'Category 2', difficulty: 'easy', question: 'What is 2 + 2?', options: ['3', '4', '5', '6'], answer: '4' },
  { category: 'Category 2', difficulty: 'easy', question: 'Who painted the Mona Lisa?', options: ['Vincent van Gogh', 'Pablo Picasso', 'Leonardo da Vinci', 'Claude Monet'], answer: 'Leonardo da Vinci' },
  { category: 'Category 2', difficulty: 'easy', question: 'Which country is known as the Land of the Rising Sun?', options: ['China', 'Japan', 'India', 'South Korea'], answer: 'Japan' },
  { category: 'Category 2', difficulty: 'easy', question: 'Which gas do plants absorb from the atmosphere?', options: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen'], answer: 'Carbon dioxide' },

  // Category 1 - Medium
  { category: 'Category 2', difficulty: 'medium', question: 'What year did World War II end?', options: ['1944', '1945', '1946', '1947'], answer: '1945' },
  { category: 'Category 2', difficulty: 'medium', question: 'What is the smallest planet in our solar system?', options: ['Earth', 'Venus', 'Mars', 'Mercury'], answer: 'Mercury' },
  { category: 'Category 2', difficulty: 'medium', question: 'Who is the author of "The Hobbit"?', options: ['J.R.R. Tolkien', 'J.K. Rowling', 'George R.R. Martin', 'Mark Twain'], answer: 'J.R.R. Tolkien' },
  { category: 'Category 2', difficulty: 'medium', question: 'What is the hardest natural substance on Earth?', options: ['Iron', 'Gold', 'Diamond', 'Silver'], answer: 'Diamond' },
  { category: 'Category 2', difficulty: 'medium', question: 'Which country hosted the 2016 Summer Olympics?', options: ['China', 'Brazil', 'UK', 'Japan'], answer: 'Brazil' },
  { category: 'Category 2', difficulty: 'medium', question: 'What is the chemical symbol for water?', options: ['O2', 'CO2', 'H2O', 'H2'], answer: 'H2O' },
  { category: 'Category 2', difficulty: 'medium', question: 'Who discovered penicillin?', options: ['Marie Curie', 'Alexander Fleming', 'Isaac Newton', 'Albert Einstein'], answer: 'Alexander Fleming' },
  { category: 'Category 2', difficulty: 'medium', question: 'What is the longest river in the world?', options: ['Amazon', 'Nile', 'Yangtze', 'Mississippi'], answer: 'Nile' },
  { category: 'Category 2', difficulty: 'medium', question: 'Which country is home to the kangaroo?', options: ['India', 'Australia', 'South Africa', 'Brazil'], answer: 'Australia' },
  { category: 'Category 2', difficulty: 'medium', question: 'What is the square root of 64?', options: ['6', '8', '10', '12'], answer: '8' },

  // Category 1 - Hard
  { category: 'Category 2', difficulty: 'hard', question: 'Who developed the theory of relativity?', options: ['Isaac Newton', 'Galileo', 'Albert Einstein', 'Marie Curie'], answer: 'Albert Einstein' },
  { category: 'Category 2', difficulty: 'hard', question: 'What is the speed of light?', options: ['300,000 km/s', '150,000 km/s', '1,000,000 km/s', '500,000 km/s'], answer: '300,000 km/s' },
  { category: 'Category 2', difficulty: 'hard', question: 'What is the capital of Canada?', options: ['Toronto', 'Ottawa', 'Vancouver', 'Montreal'], answer: 'Ottawa' },
  { category: 'Category 2', difficulty: 'hard', question: 'Who is the father of modern physics?', options: ['Albert Einstein', 'Isaac Newton', 'Galileo Galilei', 'Nikola Tesla'], answer: 'Isaac Newton' },
  { category: 'Category 2', difficulty: 'hard', question: 'What element has the atomic number 1?', options: ['Hydrogen', 'Helium', 'Oxygen', 'Nitrogen'], answer: 'Hydrogen' },
  { category: 'Category 2', difficulty: 'hard', question: 'Which country has the most pyramids?', options: ['Egypt', 'Sudan', 'Mexico', 'China'], answer: 'Sudan' },
  { category: 'Category 2', difficulty: 'hard', question: 'Who wrote the play "Hamlet"?', options: ['William Shakespeare', 'Jane Austen', 'Mark Twain', 'Charles Dickens'], answer: 'William Shakespeare' },
  { category: 'Category 2', difficulty: 'hard', question: 'What is the square root of 144?', options: ['10', '12', '14', '16'], answer: '12' },
  { category: 'Category 2', difficulty: 'hard', question: 'What is the largest mammal?', options: ['Elephant', 'Blue whale', 'Giraffe', 'Great white shark'], answer: 'Blue whale' },
  { category: 'Category 2', difficulty: 'hard', question: 'Who was the first person in space?', options: ['Neil Armstrong', 'Buzz Aldrin', 'Yuri Gagarin', 'John Glenn'], answer: 'Yuri Gagarin' },

  { category: 'Category 3', difficulty: 'easy', question: 'What is the capital of France?', options: ['Berlin', 'Madrid', 'Paris', 'Rome'], answer: 'Paris' },
  { category: 'Category 3', difficulty: 'easy', question: 'Which planet is closest to the Sun?', options: ['Venus', 'Mars', 'Mercury', 'Jupiter'], answer: 'Mercury' },
  { category: 'Category 3', difficulty: 'easy', question: 'What is the boiling point of water?', options: ['90°C', '100°C', '80°C', '70°C'], answer: '100°C' },
  { category: 'Category 3', difficulty: 'easy', question: 'Who wrote "Harry Potter"?', options: ['J.R.R. Tolkien', 'J.K. Rowling', 'George R.R. Martin', 'Suzanne Collins'], answer: 'J.K. Rowling' },
  { category: 'Category 3', difficulty: 'easy', question: 'Which ocean is the largest?', options: ['Atlantic', 'Indian', 'Pacific', 'Arctic'], answer: 'Pacific' },
  { category: 'Category 3', difficulty: 'easy', question: 'How many continents are there?', options: ['5', '6', '7', '8'], answer: '7' },
  { category: 'Category 3', difficulty: 'easy', question: 'What is 2 + 2?', options: ['3', '4', '5', '6'], answer: '4' },
  { category: 'Category 3', difficulty: 'easy', question: 'Who painted the Mona Lisa?', options: ['Vincent van Gogh', 'Pablo Picasso', 'Leonardo da Vinci', 'Claude Monet'], answer: 'Leonardo da Vinci' },
  { category: 'Category 3', difficulty: 'easy', question: 'Which country is known as the Land of the Rising Sun?', options: ['China', 'Japan', 'India', 'South Korea'], answer: 'Japan' },
  { category: 'Category 3', difficulty: 'easy', question: 'Which gas do plants absorb from the atmosphere?', options: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen'], answer: 'Carbon dioxide' },

  // Category 1 - Medium
  { category: 'Category 3', difficulty: 'medium', question: 'What year did World War II end?', options: ['1944', '1945', '1946', '1947'], answer: '1945' },
  { category: 'Category 3', difficulty: 'medium', question: 'What is the smallest planet in our solar system?', options: ['Earth', 'Venus', 'Mars', 'Mercury'], answer: 'Mercury' },
  { category: 'Category 3', difficulty: 'medium', question: 'Who is the author of "The Hobbit"?', options: ['J.R.R. Tolkien', 'J.K. Rowling', 'George R.R. Martin', 'Mark Twain'], answer: 'J.R.R. Tolkien' },
  { category: 'Category 3', difficulty: 'medium', question: 'What is the hardest natural substance on Earth?', options: ['Iron', 'Gold', 'Diamond', 'Silver'], answer: 'Diamond' },
  { category: 'Category 3', difficulty: 'medium', question: 'Which country hosted the 2016 Summer Olympics?', options: ['China', 'Brazil', 'UK', 'Japan'], answer: 'Brazil' },
  { category: 'Category 3', difficulty: 'medium', question: 'What is the chemical symbol for water?', options: ['O2', 'CO2', 'H2O', 'H2'], answer: 'H2O' },
  { category: 'Category 3', difficulty: 'medium', question: 'Who discovered penicillin?', options: ['Marie Curie', 'Alexander Fleming', 'Isaac Newton', 'Albert Einstein'], answer: 'Alexander Fleming' },
  { category: 'Category 3', difficulty: 'medium', question: 'What is the longest river in the world?', options: ['Amazon', 'Nile', 'Yangtze', 'Mississippi'], answer: 'Nile' },
  { category: 'Category 3', difficulty: 'medium', question: 'Which country is home to the kangaroo?', options: ['India', 'Australia', 'South Africa', 'Brazil'], answer: 'Australia' },
  { category: 'Category 3', difficulty: 'medium', question: 'What is the square root of 64?', options: ['6', '8', '10', '12'], answer: '8' },

  // Category 1 - Hard
  { category: 'Category 3', difficulty: 'hard', question: 'Who developed the theory of relativity?', options: ['Isaac Newton', 'Galileo', 'Albert Einstein', 'Marie Curie'], answer: 'Albert Einstein' },
  { category: 'Category 3', difficulty: 'hard', question: 'What is the speed of light?', options: ['300,000 km/s', '150,000 km/s', '1,000,000 km/s', '500,000 km/s'], answer: '300,000 km/s' },
  { category: 'Category 3', difficulty: 'hard', question: 'What is the capital of Canada?', options: ['Toronto', 'Ottawa', 'Vancouver', 'Montreal'], answer: 'Ottawa' },
  { category: 'Category 3', difficulty: 'hard', question: 'Who is the father of modern physics?', options: ['Albert Einstein', 'Isaac Newton', 'Galileo Galilei', 'Nikola Tesla'], answer: 'Isaac Newton' },
  { category: 'Category 3', difficulty: 'hard', question: 'What element has the atomic number 1?', options: ['Hydrogen', 'Helium', 'Oxygen', 'Nitrogen'], answer: 'Hydrogen' },
  { category: 'Category 3', difficulty: 'hard', question: 'Which country has the most pyramids?', options: ['Egypt', 'Sudan', 'Mexico', 'China'], answer: 'Sudan' },
  { category: 'Category 3', difficulty: 'hard', question: 'Who wrote the play "Hamlet"?', options: ['William Shakespeare', 'Jane Austen', 'Mark Twain', 'Charles Dickens'], answer: 'William Shakespeare' },
  { category: 'Category 3', difficulty: 'hard', question: 'What is the square root of 144?', options: ['10', '12', '14', '16'], answer: '12' },
  { category: 'Category 3', difficulty: 'hard', question: 'What is the largest mammal?', options: ['Elephant', 'Blue whale', 'Giraffe', 'Great white shark'], answer: 'Blue whale' },
  { category: 'Category 3', difficulty: 'hard', question: 'Who was the first person in space?', options: ['Neil Armstrong', 'Buzz Aldrin', 'Yuri Gagarin', 'John Glenn'], answer: 'Yuri Gagarin' },

];

export default questions
